# (PART) 技术专题 {.unnumbered}

# 介绍 {#part-technology .unnumbered}

\chaptermark{介绍}

```{r setup-python, echo=FALSE}
source(file = "_common.R")
# knitr::opts_chunk$set(
#   python.reticulate = TRUE
# )
# if (!is.na(Sys.getenv("CI", NA))) {
#   # Remote macOS CI 环境
#   reticulate::use_condaenv("r-reticulate", required = TRUE)
# } else {
#   # reticulate::use_python(python = Sys.getenv("RETICULATE_PYTHON"), required = TRUE)
#   reticulate::use_virtualenv(virtualenv = Sys.getenv("RETICULATE_PYTHON_ENV"), required = TRUE)
# }
```

```{css, echo=FALSE}
.modebar {
  display: none !important;
}
```

展示辛普森悖论的数据，性别歧视，公平，如何解读数据，数据会说谎。列联分析和展示。相比于 mosaicplot 有某种更加直观的含义，有人一堆堆排在那的既视感。 1973 年加州伯克利大学6个最大的院系分男女性别和是否录取统计人数，见下表

```{r}
margin.table(x = UCBAdmissions, margin = 2:1)
```

**aplpack** [@aplpack2021] 用函数 `iconplot()` 展示列联表数据，图 \@ref(fig:pictogram) 每个格子代表 100 人。

```{r pictogram, fig.width=6, fig.height=5, out.width="65%", fig.cap="加州伯克利大学的录取情况", fig.showtext=TRUE, echo=FALSE, warning=FALSE}
# library(jpeg)
# rlogo <- jpeg::readJPEG(source = system.file(package = "jpeg", "img", "Rlogo.jpg"))
# 使用 icon 替代格子
# library(aplpack)
# iconplot(
#   data = UCBAdmissions / 100, grp.color = Gender,
#   colors = c("#636363", "#BDBDBD"),
#   icons = as.raster(rlogo), 
#   main = "Student Admissions at UC Berkeley"
# )

library(aplpack)
iconplot(
  data = UCBAdmissions / 100, grp.color = Gender,
  colors = c("#636363", "#BDBDBD"),
  main = "Student Admissions at UC Berkeley"
)
```

内容上，对第一版中未介绍的部分图形予以补充，比如岭线图\@ref(fig:ridge)，单独作为技术专题的一部分。

```{r ridge, fig.width=8, fig.height=5, fig.showtext=TRUE, fig.cap="岭线图", out.width="65%", echo=FALSE}
library(ggplot2)
library(ggridges)
ggplot(data = iris, aes(x = Sepal.Length, y = Species, fill = Species)) +
  scale_fill_brewer(palette = "Greys") +
  geom_density_ridges(bandwidth = 0.2) +
  theme_ridges(font_size = 20, font_family = "Noto Sans")
```
